--- 
records: 
  - 
    email: test@test.no
    key: TEMTZpKBxQ26vzk/xs1lXyiwve8nQg3vhj6MlBP06l0=
    name: kontor.nihfregionmidt.no
    record: record
    token: token
    ttl: 1
    zone: zone
    proxied: false
settings: 
  interval: 5
